### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FrazeDev** [isPique/Net-Strike#4]
if iam correct it only sends the request from your IP?, how would you even call it a ddos if it would get affected as the modern systems are way more secured ((iam not intrested in using any ddos applications just saying))

**Comment by isPique** [comment]
It's not sending directly from your IP; instead, it's sending from multiple different random IPs while also spoofing your actual IP to hide your location.

But when it comes to HTTP-based attacks (such as HTTP GET floods), the script cannot spoof IP addresses because the TCP handshake (SYN, SYN-ACK, ACK) is needed to establish a connection, and spoofed IPs would never receive the necessary response for completing the handshake. The server would simply ignore them.

You can only use proxies in HTTP flood.

**Comment by FrazeDev** [comment]
> It's not sending directly from your IP; instead, it's sending from multiple different random IPs while also spoofing your actual IP to hide your location.
> 
> But when it comes to HTTP-based attacks (such as HTTP GET floods), the script cannot spoof IP addresses because the TCP handshake (SYN, SYN-ACK, ACK) is needed to establish a connection, and spoofed IPs would never receive the necessary response for completing the handshake. The server would simply ignore them.
> 
> You can only use proxies in HTTP flood.

Hmm, interesting thanks for responding :)
